import './globals.css';

import { Inter } from 'next/font/google';
import { Header } from '@/components';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Thought Share',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <Header />
        <div>{children}</div>
      </body>
    </html>
  );
}
